# Generated by Django 5.2.15 on 2026-06-14 20:26

import uuid
from django.db import migrations, models


def set_uuids(apps, _schema_editor):
    Order = apps.get_model("shop", "Order")
    for order in Order.objects.all():
        order.uuid = uuid.uuid4()
        order.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(set_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
